name: Deploy

on: [push]
#  push:
#    tags:
#      - '**'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install and build
        run: |
          npm ci
          npm run build:js --if-present
      - uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/marking-ts.js
          asset_name: marking-ts.js
          tag: ${{ github.ref }}
          overwrite: true